DDB.DVDCentral.UI/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DDB.DVDCentral.UI.Controllers
{
    public class OrderItemController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Remove(int orderItemId)
        {
            OrderItemManager.Delete(orderItemId);
            return RedirectToAction(nameof(Index), "Order");
        }

        public IActionResult Edit()
        {
            return View();
        }
    }
}

DDB.DVDCentral.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DVDCentral</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DDB.DVDCentral.UI.styles.css" asp-append-version="true" />

    <!--Data Table stuff-->
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DVDCentral</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rating" asp-action="Index">Ratings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Director" asp-action="Index">Directors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Format" asp-action="Index">Formats</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        @{
                            if (Authenticate.IsAuthenticated(HttpContextAccessor.HttpContext))
                            {
                                var fullname = HttpContextAccessor.HttpContext?.Session.GetString("fullname");
                                if (fullname != null) fullname = fullname.Replace("\"", "");
                                <li class="nav-item">
                                    <a class="nav-link text-light">@fullname</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                                </li>
                            }
                        }
                        
                        
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1">
            </div>

            <div class="col-md-2 sidebar">
                <div>
                @await Component.InvokeAsync("Sidebar")
                </div>
                <div class="shopping-cart-div">
                    @await Component.InvokeAsync("ShoppingCartComponent")
                </div>
            </div>

            <div id="overlay" onclick="off()">
                <div id="imageproplarge">
                    <img class="imageproplarge" id="output" />
                </div>

            </div>

            <div class="col-md-8 main body-content rounded-top">
                <div class="header rounded-top">
                    <h1>@ViewBag.Title</h1>
                    <h4>@ViewBag.Subject</h4>
                </div>
                <main role="main" class="pb-3">
                    <div class="text-danger">@ViewBag.Error</div>
                    @RenderBody()
                </main>
            </div>

        </div>
        
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DDB.DVDCentral.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script type="text/javascript">
    function off() {
        console.log('off');
        document.getElementById("overlay").style.display = "none";
    }

    function on(picture) {
        console.log('on');
        document.getElementById("overlay").style.display = "block";
        document.getElementById("output").src = picture;
    }
</script>

<script type="text/javascript" class="init">
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#indexDataTable').DataTable({
            "lengthMenu": [[5, 10, 25, 30, -1], [5, 10, 25, 30, "All"]]
        });
    });
</script>

<script type="text/javascript">
    function AddToCart(id) {
        $.get("/ShoppingCart/Add/" + id, function (data) {
            var cartcount = parseInt($("#cartcount").val()) + 1;
            $("#cartcount").val(cartcount);
            $("#cartcountdisp").text(cartcount + " items");
            $("#checkout-link").display("block");
            console.log(cartcount + " items");
        });
    }
</script>

DDB.DVDCentral.UI/Views/Shared/_OrderItemsEditPartial.cshtml
@model DVDCentral.BL.Models.Order

@if (Model.OrderItems.Any())
{
    <div class="row">
        <h4 class="col-md-8 rounded">Order Items:</h4>
    </div>
    <div class="row">
        <table id="orderItems" class="table data-table col-md-8">
            <thead>
                <tr>
                    <th></th>
                    <th>@Html.DisplayNameFor(Model => Model.OrderItems[0].MovieTitle)</th>
                    <th>@Html.DisplayNameFor(Model => Model.OrderItems[0].Cost)</th>
                    <th>@Html.DisplayNameFor(Model => Model.OrderItems[0].Quantity)</th>
                    <th>@Html.DisplayNameFor(Model => Model.OrderItems[0].TotalCost)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.OrderItems)
            {
                <tr>
                        <td class="col-md-2">
                            <img src="~/images/@item.MovieImagePath"
                                 class="imagepropsmall"
                                 alt="@item.MovieTitle Poster"
                                 id="movieImage" />
                        </td>
                    <td>@item.MovieTitle</td>
                    <td>$@item.Cost</td>
                    <td>@item.Quantity</td>
                    <td>$@item.TotalCost</td>
                    <td>
                            <a class="btn btn-sm btn-primary" asp-route-orderItemId="@item.Id"  asp-action="Remove" asp-controller="OrderItem">Delete</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
}

<script type="text/javascript" class="init">
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#orderItems').DataTable({
            "lengthMenu": [[5, 10, 25, 30, -1], [5, 10, 25, 30, "All"]]
        });
    });
</script>

DDB.DVDCentral.UI/Views/Shared/_OrderItemsPartial.cshtml
@model DVDCentral.BL.Models.Order

@if (Model.OrderItems.Any())
{
    <div class="row">
        <h4 class="col-md-8 rounded">Order Items:</h4>
    </div>
    <div class="row">
        <table id="orderItems" class="table data-table col-md-8">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(Model => Model.OrderItems[0].MovieTitle)</th>
                    <th>@Html.DisplayNameFor(Model => Model.OrderItems[0].Cost)</th>
                    <th>@Html.DisplayNameFor(Model => Model.OrderItems[0].Quantity)</th>
                    <th>@Html.DisplayNameFor(Model => Model.OrderItems[0].TotalCost)</th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.OrderItems)
            {
                <tr>
                    <td>@item.MovieTitle</td>
                    <td>$@item.Cost</td>
                    <td>@item.Quantity</td>
                    <td>$@item.TotalCost</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
}

<script type="text/javascript" class="init">
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#orderItems').DataTable({
            "lengthMenu": [[5, 10, 25, 30, -1], [5, 10, 25, 30, "All"]]
        });
    });
</script>